### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by SiChiTong** [artivis/distance_map#3]
Dear Sir

   Thanks for the great work.

   May I look for any reference of the distance map ?

Regards
Don

**Comment by artivis** [comment]
Hi,  
what kind of references are you looking for ?  
Have you checked the links on the README page ?

**Comment by SiChiTong** [comment]
Dear sir

 Thanks  for your reminder!
 It have missed the hyperlink you offered in the readme

  I am looking for the SDT concepts  and theory you used in your code since I recently learning something about the oht-slam used in rescue scenario

https://github.com/autonohm/ohm_tsd_slam

 Many thanks for your awesome work and sorry for my rudeness

Regards
Don

**Comment by artivis** [comment]
Hi,
I hope the links were helpful in your research !
And don't worry you were perfectly polite ;)
Best.

**Comment by SiChiTong** [comment]
Many thanks for your kindness!
